# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TODOer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TODOer
  pod 'SwiftLint'

  target 'TODOerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TODOerUITests' do
    # Pods for testing
  end

end
